# -*- coding: utf-8 -*-
"""Pertemuan 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_ipR0-qIDri21XUbC_crFl6gXixg72m
"""



# Input
nama = input("Masukkan nama: ")
umur = int(input("Masukkan umur: "))

# Output
print("Halo", nama)
print("Umur Anda:", umur, "tahun")
print(f"Tahun lahir Anda: {2025- umur}")  # f-string

# Input dari pengguna
panjang = float(input("Masukkan panjang: "))
lebar = float(input("Masukkan lebar: "))

# Perhitungan
luas = panjang * lebar
keliling = 2 * (panjang + lebar)

# Output hasil
print(f"Luas persegi panjang: {luas}")
print(f"Keliling persegi panjang: {keliling}")

# Input dari pengguna
def lingkaran():
    print ("Menghitung Luas Lingkaran")
    r= input("Masukan jari jari ")

    Luas = (3.14*r*r)
    Keliling = (2*3.14*r)

    print ("Luas lingkaran ="),Luas
    print ("Keliling lingkaran ="),Keliling

lingkaran()

def luas_lingkaran():
	jari_jari = int(input("Masukan jari-jari lingkaran: "))
	luas = 22/7 * (float(jari_jari) ** 2)
	print("Hasilnya adalah : ", luas)
	return luas

def keliling_lingkaran():
	jari_jari2 = int(input("Masukan jari-jari lingkaran: "))
	keliling = 2 * 22/7 * float(jari_jari2)
	print("Hasilnya adalah : ", keliling)
	return keliling

while True:
	print("====== SELAMAT DATANG DI PROGRAM LINGKARAN ======")
	print("Berikut adalah menu yang tersedia:")
	print("1. Mencari luas Lingkaran")
	print("2. Mencari keliling Lingkaran")
	print("3. Batal")
	option = input("Option 1-2 : ")
	if option == "1":
		print("Anda Pilih Menu 1: ")
		luas_lingkaran()
	elif option == "2":
		print("Anda Pilih Menu 2:")
		keliling_lingkaran()
	elif option == "3":
		break
	else:
		print("Keyword Anda Salah!!, Anda bisa coba lagi!!")





# bangun datar trapesium
sisi1 = int(input("Sisi 1 : "))
sisi2 = int(input("Sisi 2 : "))
sisi3 = int(input("Sisi 3 : "))
tinggi = int(input("Tinggi : "))

luas = (sisi1+sisi2) * tinggi / 2
keliling = sisi1+sisi2+sisi3+tinggi

print("Luas = ", luas)
print("Keliling =", keliling)

alas = int(input("Alas : "))
tinggi = int(input("Tinggi : "))
lebar = int(input("Lebar : "))

keliling = alas+tinggi+lebar
luas = (alas*tinggi)/2

print("Luas Segitiga Adalah : ", luas)
print("Keliling Segitiga Adalah : ", keliling)