# -*- coding: utf-8 -*-
"""Pertemuan_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rtZzIoCnHgtvaL5SNpYCo_OjKwaTx5hx
"""

def lingkaran():
    r = float(input("Masukan jari jari ? "))
    Luas = 3.14 * r * r
    Keliling = 2 * 3.14 * r
    print("Luas lingkaran =", Luas)
    print("Keliling lingkaran =", Keliling)

lingkaran()  # <-- ini penting!

def trapesium():
    print("Hitung Luas dan Keliling Trapesium")

    # Input panjang sisi
    a = float(input("Masukkan panjang sisi atas (a): "))
    b = float(input("Masukkan panjang sisi bawah (b): "))
    c = float(input("Masukkan panjang sisi miring kiri (c): "))
    d = float(input("Masukkan panjang sisi miring kanan (d): "))
    t = float(input("Masukkan tinggi trapesium (t): "))

    # Hitung luas
    luas = ((a + b) * t) / 2
    print("Luas trapesium =", luas)

    # Hitung keliling
    keliling = a + b + c + d
    print("Keliling trapesium =", keliling)

trapesium()

