# -*- coding: utf-8 -*-
"""tugas pertemuan 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JXGEziw545Yte-xYkifJzPQ7AHl86mk
"""

# Program Menampilkan Deret Fibonacci hingga n angka

def fibonacci(n):
    a, b = 0, 1
    count = 0
    while count < n:
        print(a, end=' ')
        a, b = b, a + b
        count += 1

# Input dari pengguna
n = int(input("Masukkan jumlah angka dalam deret Fibonacci: "))

if n <= 0:
    print("Masukkan bilangan bulat positif.")
else:
    print(f"Deret Fibonacci hingga {n} angka:")
    fibonacci(n)

# Input jumlah baris dari pengguna
n = int(input("Masukkan jumlah baris: "))

# Loop untuk menampilkan pola segitiga
for i in range(1, n + 1):
    print('*' * i)