# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCn_FuTuvfDN6YvYWA6sRoVhAoGf1ac8
"""

# Input
nama = input("Masukkan nama: ")
umur = int(input("Masukkan umur: "))

# Output
print("Halo", nama)
print("Umur Anda:", umur, "tahun")
print(f"Tahun lahir Anda: {2025 - umur}")  # f-string



def lingkaran():
    r = float(input("Masukan jari jari ? "))
    Luas = 3.14 * r * r
    Keliling = 2 * 3.14 * r
    print("Luas lingkaran =", Luas)
    print("Keliling lingkaran =", Keliling)

lingkaran()  # <-- ini penting!

import math

def segitiga():
    # Input panjang sisi
    a = float(input("Masukkan panjang sisi a: "))
    b = float(input("Masukkan panjang sisi b: "))
    c = float(input("Masukkan panjang sisi c: "))

    # Hitung keliling
    keliling = a + b + c
    print("Keliling segitiga =", keliling)

    # Hitung setengah keliling
    s = keliling / 2

    # Hitung luas dengan rumus Heron
    luas = math.sqrt(s * (s - a) * (s - b) * (s - c))
    print("Luas segitiga =", luas)

segitiga()

def trapesium():
    print("Hitung Luas dan Keliling Trapesium")

    # Input panjang sisi
    a = float(input("Masukkan panjang sisi atas (a): "))
    b = float(input("Masukkan panjang sisi bawah (b): "))
    c = float(input("Masukkan panjang sisi miring kiri (c): "))
    d = float(input("Masukkan panjang sisi miring kanan (d): "))
    t = float(input("Masukkan tinggi trapesium (t): "))

    # Hitung luas
    luas = ((a + b) * t) / 2
    print("Luas trapesium =", luas)

    # Hitung keliling
    keliling = a + b + c + d
    print("Keliling trapesium =", keliling)

trapesium()

import math

def operasi_dasar():
    print("\n--- Operasi Dasar ---")
    a = float(input("Masukkan angka pertama: "))
    b = float(input("Masukkan angka kedua: "))
    operator = input("Pilih operator (+, -, *, /): ")

    if operator == "+":
        hasil = a + b
    elif operator == "-":
        hasil = a - b
    elif operator == "*":
        hasil = a * b
    elif operator == "/":
        if b != 0:
            hasil = a / b
        else:
            hasil = "Error: Pembagi tidak boleh nol!"
    else:
        hasil = "Operator tidak valid."

    print("Hasil:", hasil)

def perpangkatan_akar():
    print("\n--- Perpangkatan dan Akar Kuadrat ---")
    pilihan = input("Ketik 'pangkat' untuk perpangkatan atau 'akar' untuk akar kuadrat: ").lower()

    if pilihan == "pangkat":
        angka = float(input("Masukkan angka: "))
        pangkat = float(input("Masukkan pangkat: "))
        hasil = angka ** pangkat
        print(f"Hasil: {angka}^{pangkat} = {hasil}")
    elif pilihan == "akar":
        angka = float(input("Masukkan angka: "))
        hasil = math.sqrt(angka)
        print(f"Akar kuadrat dari {angka} = {hasil}")
    else:
        print("Pilihan tidak valid.")

def konversi_suhu():
    print("\n--- Konversi Suhu ---")
    suhu = float(input("Masukkan suhu: "))
    asal = input("Dari satuan (C/F/K): ").upper()
    tujuan = input("Ke satuan (C/F/K): ").upper()

    hasil = None

    if asal == "C":
        if tujuan == "F":
            hasil = (suhu * 9/5) + 32
        elif tujuan == "K":
            hasil = suhu + 273.15
        elif tujuan == "C":
            hasil = suhu
    elif asal == "F":
        if tujuan == "C":
            hasil = (suhu - 32) * 5/9
        elif tujuan == "K":
            hasil = (suhu - 32) * 5/9 + 273.15
        elif tujuan == "F":
            hasil = suhu
    elif asal == "K":
        if tujuan == "C":
            hasil = suhu - 273.15
        elif tujuan == "F":
            hasil = (suhu - 273.15) * 9/5 + 32
        elif tujuan == "K":
            hasil = suhu
    else:
        print("Satuan tidak dikenal!")

    if hasil is not None:
        print(f"Hasil: {hasil}°{tujuan}")

def kalkulator():
    while True:
        print("\n===== Kalkulator Multifungsi =====")
        print("1. Operasi Dasar (+, -, *, /)")
        print("2. Perpangkatan & Akar Kuadrat")
        print("3. Konversi Suhu")
        print("4. Keluar")

        pilihan = input("Pilih menu (1/2/3/4): ")

        if pilihan == "1":
            operasi_dasar()
        elif pilihan == "2":
            perpangkatan_akar()
        elif pilihan == "3":
            konversi_suhu()
        elif pilihan == "4":
            print("Terima kasih, sampai jumpa!")
            break
        else:
            print("Pilihan tidak valid!")

kalkulator()



"""Sistem Informasi Akademik

Nama Mahasiswa → String / Text

NIM (Nomor Induk Mahasiswa) → String

Tanggal Lahir → Date

IPK (Indeks Prestasi) → Float (contoh: 3.75)

Jumlah SKS → Integer

Status Lulus / Tidak → Boolean (True / False)

Aplikasi E-Commerce

Nama Produk → String

Harga Produk → Float atau Decimal (untuk akurasi uang)

Stok Barang → Integer

Deskripsi Produk → Text

Status Tersedia / Tidak → Boolean

Tanggal Transaksi → DateTime

Rating Produk → Float (contoh: 4.5)

Gambar Produk → Blob (untuk file gambar di database) atau String (URL gambar)

Sistem Reservasi Hotel
Biasanya berisi data seperti:

Nama Tamu → String

Nomor Kamar → Integer atau String (kalau pakai kode unik seperti A101)

Tanggal Check-in / Check-out → DateTime

Jumlah Orang → Integer

Harga Sewa per Malam → Float atau Decimal

Status Pemesanan → Boolean (Contoh: True = Sudah Dibayar)

Catatan Khusus / Permintaan Tambahan → Text
"""

def hitung_nilai():
    tugas = float(input("Masukkan nilai Tugas (0-100): "))
    uts = float(input("Masukkan nilai UTS (0-100): "))
    uas = float(input("Masukkan nilai UAS (0-100): "))

    total = (tugas * 0.3) + (uts * 0.3) + (uas * 0.4)

    if total >= 85:
        kategori = "A (Sangat Baik)"
    elif total >= 75:
        kategori = "B (Baik)"
    elif total >= 65:
        kategori = "C (Cukup)"
    elif total >= 50:
        kategori = "D (Kurang)"
    else:
        kategori = "E (Gagal)"

    print(f"Total Nilai: {total}")
    print(f"Kategori Nilai: {kategori}")

hitung_nilai()

saldo = 5000000
pin = "1234"

def verifikasi_pin():
    user_pin = input("Masukkan PIN: ")
    return user_pin == pin

def atm():
    global saldo, pin
    if not verifikasi_pin():
        print("PIN salah! Akses ditolak.")
        return

    while True:
        print("\n=== Menu ATM ===")
        print("1. Cek Saldo")
        print("2. Tarik Tunai")
        print("3. Setor Tunai")
        print("4. Transfer")
        print("5. Ganti PIN")
        print("6. Keluar")

        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            print(f"Saldo Anda: Rp {saldo}")
        elif pilihan == "2":
            nominal = int(input("Masukkan nominal tarik tunai: "))
            if nominal <= saldo:
                saldo -= nominal
                print(f"Penarikan berhasil! Saldo tersisa: Rp {saldo}")
            else:
                print("Saldo tidak cukup!")
        elif pilihan == "3":
            nominal = int(input("Masukkan nominal setor tunai: "))
            saldo += nominal
            print(f"Setoran berhasil! Saldo sekarang: Rp {saldo}")
        elif pilihan == "4":
            rekening = input("Masukkan no rekening tujuan: ")
            nominal = int(input("Masukkan nominal transfer: "))
            if nominal <= saldo:
                saldo -= nominal
                print(f"Transfer Rp {nominal} ke rekening {rekening} berhasil!")
            else:
                print("Saldo tidak cukup untuk transfer!")
        elif pilihan == "5":
            pin_lama = input("Masukkan PIN lama: ")
            if pin_lama == pin:
                pin_baru = input("Masukkan PIN baru: ")
                pin = pin_baru
                print("PIN berhasil diganti.")
            else:
                print("PIN lama salah!")
        elif pilihan == "6":
            print("Terima kasih telah menggunakan ATM.")
            break
        else:
            print("Menu tidak tersedia!")

atm()

a = int(input("Masukkan bilangan pertama: "))
b = int(input("Masukkan bilangan kedua: "))
c = int(input("Masukkan bilangan ketiga: "))

if a > b:
    if a > c:
        maks = a
    else:
        maks = c
else:
    if b > c:
        maks = b
    else:
        maks = c

print("Nilai maksimum adalah:", maks)

#operator logika
a = int(input("Masukkan bilangan pertama: "))
b = int(input("Masukkan bilangan kedua: "))
c = int(input("Masukkan bilangan ketiga: "))

if a >= b and a >= c:
    maks = a
elif b >= a and b >= c:
    maks = b
else:
    maks = c

print("Nilai maksimum adalah:", maks)

#Fungsi max()
a = int(input("Masukkan bilangan pertama: "))
b = int(input("Masukkan bilangan kedua: "))
c = int(input("Masukkan bilangan ketiga: "))

maks = max(a, b, c)
print("Nilai maksimum adalah:", maks)