# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ri7YJ5ie4CD-eqZXUgGHtp_Lf4sZTkhr
"""

# Pertemuan 5 Array & String
# 1. Operasi Matrix
class MatrixOperations:
    @staticmethod
    def add(matrix1, matrix2):
        """Penjumlahan dua matriks"""
        if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
            raise ValueError("Ukuran matriks tidak sama")
        return [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]

    @staticmethod
    def subtract(matrix1, matrix2):
        """Pengurangan dua matriks"""
        if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
            raise ValueError("Ukuran matriks tidak sama")
        return [[matrix1[i][j] - matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]

    @staticmethod
    def multiply(matrix1, matrix2):
        """Perkalian dua matriks"""
        if len(matrix1[0]) != len(matrix2):
            raise ValueError("Jumlah kolom matriks pertama harus sama dengan jumlah baris matriks kedua")
        return [[sum(a*b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]

    @staticmethod
    def find_max_min(array):
        """Mencari nilai maksimum dan minimum dalam array"""
        if not array:
            return None, None
        return max(array), min(array)

# Contoh penggunaan
if __name__ == "__main__":
    # Operasi matriks
    mat1 = [[1, 2], [3, 4]]
    mat2 = [[5, 6], [7, 8]]

    print("Penjumlahan:", MatrixOperations.add(mat1, mat2))
    print("Pengurangan:", MatrixOperations.subtract(mat1, mat2))
    print("Perkalian:", MatrixOperations.multiply(mat1, mat2))

    # Mencari max dan min array
    arr = [3, 1, 4, 1, 5, 9, 2, 6]
    max_val, min_val = MatrixOperations.find_max_min(arr)
    print(f"Array: {arr}")
    print(f"Max: {max_val}, Min: {min_val}")

def cari_maks_min(arr):
    maksimum = max(arr)
    minimum = min(arr)
    return maksimum, minimum

# Contoh penggunaan
array = [5, 2, 9, 1, 7]
maks, mins = cari_maks_min(array)
print(f"Nilai maksimum: {maks}")
print(f"Nilai minimum: {mins}")

def hitung_statistik(teks):
    jumlah_kata = len(teks.split())
    jumlah_karakter = len(teks)
    jumlah_kalimat = teks.count('.') + teks.count('!') + teks.count('?')
    return jumlah_kata, jumlah_karakter, jumlah_kalimat

def cari_kata(teks, kata):
    return kata in teks

def ganti_teks(teks, cari, ganti):
    return teks.replace(cari, ganti)

def format_teks(teks, mode):
    if mode == "uppercase":
        return teks.upper()
    elif mode == "lowercase":
        return teks.lower()
    elif mode == "titlecase":
        return teks.title()
    else:
        return teks

# Program utama
teks_input = input("Masukkan teks: ")

# Statistik
kata, karakter, kalimat = hitung_statistik(teks_input)
print(f"Jumlah kata: {kata}")
print(f"Jumlah karakter: {karakter}")
print(f"Jumlah kalimat: {kalimat}")

# Pencarian kata
kata_dicari = input("Masukkan kata yang ingin dicari: ")
ditemukan = cari_kata(teks_input, kata_dicari)
print(f"Kata ditemukan: {ditemukan}")

# Penggantian teks
cari = input("Masukkan kata yang ingin diganti: ")
ganti = input("Masukkan kata pengganti: ")
teks_baru = ganti_teks(teks_input, cari, ganti)
print("Teks setelah penggantian:", teks_baru)

# Format teks
mode = input("Pilih format (uppercase/lowercase/titlecase): ")
teks_format = format_teks(teks_baru, mode)
print("Teks setelah format:", teks_format)